# Generated by Django 4.0.3 on 2022-03-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
