# Generated by Django 4.0.3 on 2022-03-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_employee_user_name_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=60)),
                ('Emp_role', models.CharField(max_length=60)),
                ('Emp_department', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=160)),
                ('business_partner', models.CharField(max_length=160)),
                ('order_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Total_price', models.IntegerField()),
                ('Country', models.CharField(max_length=150)),
                ('Phone_number', models.IntegerField()),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.employee')),
            ],
        ),
    ]
